### ISSUE TITLE
An Api

### ISSUE THREAD

**Issue by BLAST1718** [HimmelKreis4865/BetterSkulls#1]
Make an api so we can do something like when the player dies their skull get dropped

**Comment by HimmelKreis4865** [comment]
Hey, 

Sorry for the late response! I might add some more Events to simplify the API, but regarding the example you said, that's aready possible:
```php
$item = HimmelKreis4865\BetterSkulls\BetterSkulls::constructPlayerHeadItem($player->getName(), $player->getSkin());
```
You got any other wishes?

**Comment by BLAST1718** [comment]
[06:03:30] [Server thread/CRITICAL]: Error: "Class 'TheBlast\SkyBlockGui\HimmelKreis4865\BetterSkulls\BetterSkulls' not found" (EXCEPTION) in "plugins/SkyBlock Menu/src/TheBlast/SkyBlockGui/Main" at line 1415

gives me these error even though i have the use

**Comment by HimmelKreis4865** [comment]
Add a backslash `\` before HimmelKreis4865 in the same above, or just remove `HimmelKreis4865\BetterSkulls\`

**Comment by BLAST1718** [comment]
Ye I fixed it someone told me how

**Comment by HimmelKreis4865** [comment]
Okey, so this is done now or do you have any other wishes?
