### ISSUE TITLE
Skull's name can be changeable 

### ISSUE THREAD

**Issue by Adam1609** [HimmelKreis4865/BetterSkulls#2]
**Is your feature request related to a problem? Please describe.**
When creating a skull, when changing skull's name, then placing it. Break it will convert back into old name.

**Describe the solution you'd like**
When creating skull, it would be good to add a custom name into it, and when you want to break the skull, it will turn into the name you just changed

**Describe alternatives you've considered**

**Additional context**

**Comment by HimmelKreis4865** [comment]
Hello, so I do understand your problem, but you might only want to change the format of the itemname right? 
Bc username is stored in a separate NBT tag - I don't use customnames for it.

If you only want to change colors / the words on the name for any skull: I marked is as todo for me, It's going to be added in a few days.
Or would you like individual name support?

**Comment by Adam1609** [comment]
'If you only want to change colors / the words on the name for any skull: I marked is as todo for me, It's going to be added in a few days.'

That's my suggestion, it would be good to add

**Comment by HimmelKreis4865** [comment]
Okay, was less work then expected, delete your config.yml, upload the new version, restart the server and you should now be able to change the itemname ^^
If you got any other suggestions you're welcome to write them down here
