### ISSUE TITLE
Kopfentity Bug mit Worldedit

### ISSUE THREAD

**Issue by DramaLvl1** [HimmelKreis4865/BetterSkulls#5]
Wenn man die Köpfe mit Worldedit entfernt, bleibt der Entity dort für immer.
Kann man was dagegen tuen? 😅

**Comment by HimmelKreis4865** [comment]
Je nachdem wie die Blöcke vom Worldedit plugin bearbeitet werden, wird `Level->setBlock()` / `Level->setBlockIdAt()` benutzt kann man das theoretisch ändern, aber da die meisten die (sub)chunks nutzen würde es hier nicht gehen. Du könntest allerdings während das Worldedit die Blöcke entfernt auch die Entities in der Area entfernen
