### ISSUE TITLE
[BUG:] Head Entities collect xp

### ISSUE THREAD

**Issue by supercrafter333** [HimmelKreis4865/BetterSkulls#6]
**Describe the bug**
If xp is laying anywhere and a Head entitie is after there, the entitie will collect the xp.

**To Reproduce**
1. Spawn xp orbs
2. The entities will collect it
3. TryItAndSee

**Expected behavior**
---

**Screenshots**
--- Not needet ---

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04
 - PHP Version: 7.4
 - PocketMine-MP Versi**o**n: 3.18.1

**Additional context**
---

**Comment by HimmelKreis4865** [comment]
I see the issue, I gonna work on it later on ^^

**Comment by supercrafter333** [comment]
:)

**Comment by HimmelKreis4865** [comment]
so this is currently a bug of pocketmine, I wanted to make a pr but its disabled rn which means you'll have to wait until it's open again

**Comment by supercrafter333** [comment]
Good :)
