### ISSUE TITLE
[BUG:] Sceletons snipes Head Entities

### ISSUE THREAD

**Issue by supercrafter333** [HimmelKreis4865/BetterSkulls#7]
**Describe the bug**
With PureEntitiesX spawned entities try to snipe Head entites, that's funny but It's a bug.

**To Reproduce**
1. Spawn a sceleton near a Head entitie
2. Look...

**Expected behavior**
---

**Screenshots**
--- Not needed ---

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04
 - PHP Version**:** 7.4
 - PocketMine-MP Versi**~~o~~**n: 3.18.1

**Additional context**
---

**Comment by HimmelKreis4865** [comment]
This error is not caused by BetterSkulls & I can't fix it since there is no implemented method for making it attackable or something, you might open an issue on PureEntitiesX

**Comment by supercrafter333** [comment]
I think it's not only a bug caused by PureEntitiesX

**Comment by HimmelKreis4865** [comment]
not only, but i definitly cant do anything here
